org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
kotlin.daemon.jvmargs=-Xmx1024m
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.enableJetifier=true

systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.https.socketTimeout=120000
systemProp.https.connectionTimeout=120000